### ISSUE TITLE
Projekte JF am 26.03.2018 Adaptions NetFlower 

### ISSUE THREAD

**Issue by NChristina** [VALIDproject/netflower#162]
![2018-03-27 10 29 03](https://user-images.githubusercontent.com/18003747/37955652-78a125ce-31a9-11e8-968c-3a97b460513f.jpg)

**Comment by alex-rind** [comment]
**CSV unescaped comma**
I can only partially reproduce the issue. Our code calls [d3.csv.format()](https://github.com/d3/d3-3.x-api-reference/blob/master/CSV.md#format), which surrounds node names like "Bundesministerium für Arbeit, Soziales, Gesundheit und Konsumentenschutz" with quotation marks, so I can import it into datawrapper or LibreOffice Calc. Opening it in German-speaking Excel by double-click fails because it expects a semicolon. Opening via `Daten > Aus Text` works fine.

d3.tsv.format() will produces a tab-separated file that handles columns fine (also in German Excel default) but other issues remain (unicode characters; number format).

**Comment by doomsayer2** [comment]
- [ ] Nur ausgewählte Nodes (search adaptation)
- [ ] Reihenfolge ändern (optimization)
- [ ] Sparkline Hover erreichbar machen
- [ ] Tagging umbauen
- [ ] CSV trennung ändern
